In [1]:
import tensorflow as tf
from transformers import TFMT5Model, MT5Tokenizer, T5Tokenizer, MT5Config

C:\Users\PedroAntonio\Anaconda3\envs\proj\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
model_path = 'google/mt5-small'

In [3]:
# tokenizer = T5Tokenizer.from_pretrained(model_path)
model = TFMT5Model.from_pretrained(model_path)

Downloading: 100%|██████████| 1.12G/1.12G [05:35<00:00, 3.58MB/s]
Some layers from the model checkpoint at google/mt5-small were not used when initializing TFMT5Model: ['lm_head']
- This IS expected if you are initializing TFMT5Model from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFMT5Model from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFMT5Model were initialized from the model checkpoint at google/mt5-small.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFMT5Model for predictions without further training.


In [4]:
model.save_pretrained("models/mt5-small")

In [3]:
model1 = TFMT5Model.from_pretrained('models/mt5-small')

All model checkpoint layers were used when initializing TFMT5Model.

All the layers of TFMT5Model were initialized from the model checkpoint at models/mt5-small.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFMT5Model for predictions without further training.


In [6]:
tf.keras.models.load_model('models/mt5-small')

OSError: SavedModel file does not exist at: models/mt5-small\{saved_model.pbtxt|saved_model.pb}

In [4]:
tokenizer = T5Tokenizer.from_pretrained("google/mt5-small")

Downloading: 100%|██████████| 4.11M/4.11M [00:01<00:00, 3.13MB/s]
Downloading: 100%|██████████| 99.0/99.0 [00:00<00:00, 28.5kB/s]
Downloading: 100%|██████████| 82.0/82.0 [00:00<00:00, 55.1kB/s]


In [5]:
tokenizer.save_pretrained("models/mt5-small-tok")

('models/mt5-small-tok\\tokenizer_config.json',
 'models/mt5-small-tok\\special_tokens_map.json',
 'models/mt5-small-tok\\spiece.model',
 'models/mt5-small-tok\\added_tokens.json')

In [8]:
article = "UN Offizier sagt, dass weiter verhandelt werden muss in Syrien."
summary = "Weiter Verhandlung in Syrien."
inputs = tokenizer(article, return_tensors="tf")
with tokenizer.as_target_tokenizer():
    labels = tokenizer(summary, return_tensors="tf")
    outputs = model1(input_ids=inputs["input_ids"], decoder_input_ids=labels["input_ids"])
print(outputs)

TFSeq2SeqModelOutput(last_hidden_state=<tf.Tensor: shape=(1, 7, 512), dtype=float32, numpy=
array([[[-0.47903135, -0.02558051, -0.39100158, ...,  0.06961741,
          0.15487526,  0.5829126 ],
        [-0.14677024,  0.5403384 , -0.326302  , ...,  0.13976954,
         -0.09569693,  0.39440426],
        [-0.04597886,  0.42806092, -0.27955127, ...,  0.1270425 ,
          0.01628425,  0.43063888],
        ...,
        [ 0.0907893 ,  0.26754805, -0.2021508 , ...,  0.28621534,
         -0.1342488 ,  0.48678318],
        [-0.23920135,  0.19521311, -0.01796343, ...,  0.24242437,
          0.24405766,  0.19067392],
        [-0.34046584,  0.16113949,  0.39452645, ..., -0.05173278,
          0.07799101, -0.16658998]]], dtype=float32)>, past_key_values=((<tf.Tensor: shape=(1, 6, 7, 64), dtype=float32, numpy=
array([[[[ 5.97038627e-01,  5.70536077e-01,  3.03846478e-01, ...,
          -1.14043665e+00,  1.48849905e+00, -3.60149324e-01],
         [ 4.13305461e-01, -3.51554573e-01, -7.38654852e-01, ..