In [22]:
import tensorflow as tf
from transformers import TFMT5Model, MT5Tokenizer, T5Tokenizer, MT5Config,MT5ForConditionalGeneration

In [2]:
model_path = 'google/mt5-small'

In [3]:
# tokenizer = T5Tokenizer.from_pretrained(model_path)
#model = TFMT5Model.from_pretrained(model_path)

Downloading: 100%|██████████| 1.12G/1.12G [05:35<00:00, 3.58MB/s]
Some layers from the model checkpoint at google/mt5-small were not used when initializing TFMT5Model: ['lm_head']
- This IS expected if you are initializing TFMT5Model from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFMT5Model from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFMT5Model were initialized from the model checkpoint at google/mt5-small.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFMT5Model for predictions without further training.


In [4]:
#model.save_pretrained("models/mt5-small")

In [10]:
model1 = TFMT5Model.from_pretrained('models/mt5-small')

All model checkpoint layers were used when initializing TFMT5Model.

All the layers of TFMT5Model were initialized from the model checkpoint at models/mt5-small.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFMT5Model for predictions without further training.


In [11]:
tf.keras.models.load_model('models/mt5-small')

OSError: SavedModel file does not exist at: models/mt5-small\{saved_model.pbtxt|saved_model.pb}

In [4]:
#tokenizer = T5Tokenizer.from_pretrained("google/mt5-small")

Downloading: 100%|██████████| 4.11M/4.11M [00:01<00:00, 3.13MB/s]
Downloading: 100%|██████████| 99.0/99.0 [00:00<00:00, 28.5kB/s]
Downloading: 100%|██████████| 82.0/82.0 [00:00<00:00, 55.1kB/s]


In [5]:
#tokenizer.save_pretrained("models/mt5-small-tok")

('models/mt5-small-tok\\tokenizer_config.json',
 'models/mt5-small-tok\\special_tokens_map.json',
 'models/mt5-small-tok\\spiece.model',
 'models/mt5-small-tok\\added_tokens.json')

In [12]:
tokenizer = MT5Tokenizer.from_pretrained('models/mt5-small-tok')

In [21]:
article = "UN Offizier sagt, dass weiter verhandelt werden muss in Syrien."
summary = "Weiter Verhandlung in Syrien."
inputs = tokenizer(article, return_tensors="tf")
with tokenizer.as_target_tokenizer():
    labels = tokenizer(summary, return_tensors="tf")
    outputs = model1(input_ids=inputs["input_ids"], decoder_input_ids=labels["input_ids"])
print(outputs)

TFSeq2SeqModelOutput(last_hidden_state=<tf.Tensor: shape=(1, 7, 512), dtype=float32, numpy=
array([[[-0.47903293, -0.02558335, -0.39100182, ...,  0.06961575,
          0.15487614,  0.582913  ],
        [-0.14677025,  0.5403384 , -0.3263021 , ...,  0.13976943,
         -0.09569719,  0.39440438],
        [-0.04597844,  0.4280616 , -0.27955142, ...,  0.12704314,
          0.0162837 ,  0.4306387 ],
        ...,
        [ 0.09079006,  0.26754823, -0.202152  , ...,  0.28621548,
         -0.13424923,  0.4867837 ],
        [-0.23920238,  0.19521677, -0.01796488, ...,  0.24242596,
          0.24405673,  0.1906764 ],
        [-0.34046578,  0.1611395 ,  0.39452633, ..., -0.05173289,
          0.07799099, -0.16658993]]], dtype=float32)>, past_key_values=((<tf.Tensor: shape=(1, 6, 7, 64), dtype=float32, numpy=
array([[[[ 5.97038627e-01,  5.70536077e-01,  3.03846478e-01, ...,
          -1.14043665e+00,  1.48849905e+00, -3.60149324e-01],
         [ 4.13305461e-01, -3.51554573e-01, -7.38654852e-01, ..

In [36]:
from transformers import MT5Tokenizer, TFMT5ForConditionalGeneration
model = TFMT5ForConditionalGeneration.from_pretrained('google/mt5-base')
tokenizer = MT5Tokenizer.from_pretrained('google/mt5-base', use_fast=True)

input_ids = tokenizer.encode("What the <extra_id_0> is going on inside this <extra_id_1> ?", return_tensors="tf")

output_ids = model.generate(input_ids)
print(tokenizer.batch_decode(output_ids))

['<pad> <extra_id_0> heck <extra_id_1> aquarium <extra_id_2> aquarium <extra_id_3>?</s>']


In [44]:
# https://github.com/huggingface/transformers/issues/8704
# https://huggingface.co/docs/transformers/tasks/translation
from transformers import TFT5ForConditionalGeneration, T5Tokenizer
model = TFT5ForConditionalGeneration.from_pretrained('t5-small')
tokenizer = T5Tokenizer.from_pretrained("t5-small")
article = "translate to french: The capital of France is Paris."
batch = tokenizer.prepare_seq2seq_batch(src_texts=[article], return_tensors="tf")
output_ids = model.generate(input_ids=batch.input_ids, num_return_sequences=1, num_beams=8, length_penalty=0.1)
tokenizer.decode(output_ids[0])


Downloading:   0%|          | 0.00/231M [00:00<?, ?B/s]
Downloading:   0%|          | 622k/231M [00:00<00:38, 6.36MB/s]
Downloading:   1%|          | 1.47M/231M [00:00<00:30, 7.92MB/s]
Downloading:   1%|          | 2.38M/231M [00:00<00:27, 8.68MB/s]
Downloading:   1%|▏         | 3.21M/231M [00:00<00:28, 8.37MB/s]
Downloading:   2%|▏         | 4.01M/231M [00:00<00:29, 8.17MB/s]
Downloading:   2%|▏         | 4.95M/231M [00:00<00:27, 8.66MB/s]
Downloading:   3%|▎         | 5.92M/231M [00:00<00:25, 9.14MB/s]
Downloading:   3%|▎         | 6.98M/231M [00:00<00:24, 9.76MB/s]
Downloading:   3%|▎         | 7.95M/231M [00:00<00:23, 9.86MB/s]
Downloading:   4%|▍         | 9.06M/231M [00:01<00:22, 10.4MB/s]
Downloading:   4%|▍         | 10.2M/231M [00:01<00:21, 10.8MB/s]
Downloading:   5%|▍         | 11.3M/231M [00:01<00:20, 11.0MB/s]
Downloading:   5%|▌         | 12.3M/231M [00:01<00:21, 10.9MB/s]
Downloading:   6%|▌         | 13.4M/231M [00:01<00:21, 10.8MB/s]
Downloading:   6%|▌         | 14.4

Downloading:  58%|█████▊    | 134M/231M [00:12<00:08, 12.1MB/s]
Downloading:  58%|█████▊    | 135M/231M [00:12<00:08, 12.1MB/s]
Downloading:  59%|█████▉    | 136M/231M [00:12<00:08, 12.1MB/s]
Downloading:  59%|█████▉    | 137M/231M [00:12<00:08, 12.0MB/s]
Downloading:  60%|█████▉    | 138M/231M [00:12<00:08, 11.6MB/s]
Downloading:  61%|██████    | 140M/231M [00:13<00:07, 12.3MB/s]
Downloading:  61%|██████    | 141M/231M [00:13<00:07, 12.0MB/s]
Downloading:  62%|██████▏   | 142M/231M [00:13<00:07, 12.2MB/s]
Downloading:  62%|██████▏   | 143M/231M [00:13<00:07, 12.1MB/s]
Downloading:  63%|██████▎   | 145M/231M [00:13<00:07, 12.0MB/s]
Downloading:  63%|██████▎   | 146M/231M [00:13<00:07, 12.0MB/s]
Downloading:  64%|██████▎   | 147M/231M [00:13<00:07, 11.9MB/s]
Downloading:  64%|██████▍   | 148M/231M [00:13<00:07, 11.9MB/s]
Downloading:  65%|██████▍   | 149M/231M [00:13<00:07, 11.6MB/s]
Downloading:  65%|██████▌   | 150M/231M [00:13<00:07, 11.8MB/s]
Downloading:  66%|██████▌   | 151M/231M 

'<pad> La capitale de la France est Paris.'

In [51]:
article = "translate to german: killing two birds with one stone"
batch = tokenizer.prepare_seq2seq_batch(src_texts=[article], return_tensors="tf")
output_ids = model.generate(input_ids=batch.input_ids, num_return_sequences=1, num_beams=8, length_penalty=0.1)
tokenizer.decode(output_ids[0])

'<pad> 2 Vögel mit einem Stein zu töten'